# Generated by Django 4.2.5 on 2023-11-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('system_id', models.CharField(max_length=200)),
                ('configuration', models.CharField(max_length=200)),
                ('system_tree_item', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user_text22_failure_detection_situation', models.CharField(blank=True, max_length=200, null=True)),
                ('user_text23_failure_buque_situation', models.CharField(blank=True, max_length=200, null=True)),
                ('user_text24_failure_effect_item', models.CharField(blank=True, max_length=200, null=True)),
                ('user_text25_failure_evidence', models.CharField(blank=True, max_length=200, null=True)),
                ('occurrence_date', models.DateTimeField()),
                ('occurrence_time', models.CharField(blank=True, max_length=200, null=True)),
                ('description_incident', models.TextField(blank=True, null=True)),
                ('user_text26_user_failure_detection', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_ID', models.CharField(max_length=200)),
                ('maintenance_log_identifier', models.CharField(max_length=200)),
                ('override_system_tree_item_replaced_part', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_item', models.FloatField(blank=True, null=True)),
                ('number_of_men', models.IntegerField(blank=True, null=True)),
                ('elapsed_maintenance_time', models.FloatField(blank=True, null=True)),
                ('action_taken_maintenace', models.CharField(blank=True, max_length=200, null=True)),
                ('total_maintenance_time', models.FloatField(blank=True, null=True)),
                ('user_value2_total_maintenance_time', models.FloatField(blank=True, null=True)),
                ('cost_maintenance', models.FloatField(blank=True, null=True)),
                ('maintenance_start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OperatingTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('configuration', models.CharField(max_length=200)),
                ('user_text1_tail_number', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('multiplicative_djustment', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
