# Generated by Django 4.2.5 on 2023-11-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceLogs',
            new_name='MaintenanceLog',
        ),
        migrations.RenameModel(
            old_name='OperatingTimes',
            new_name='OperatingTime',
        ),
    ]
